# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2a998c5e87f172ea9744cc086ba7eec09b18e9f82e50f2775b077a2b3d9c7aa65a18b3395d9b955f9face8a1801be5b171c949a85e40822764548043bce05d5

test:
  secret_key_base: 1edd347f6d320eeff20f3bd8061e3b830899de9fb24288e2aefe824672ff3a1b80b562a8861b48dcc00867ddbb9e364e900c87df87a993efaf32c171e3a0cbd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
